config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'home/about' => 'homes#about', as: "about_home"

  root to: 'homes#top'

  resources :books, only: [:new, :index, :show, :create, :edit, :destroy, :edit, :update]

  resources :users, only: [:index, :show, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top ,:about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]


  def new
  end

  def index
    @user = User.find(current_user.id.to_s)
    @book_new = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find_by(id: params[:id])
    @user = @book.user
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      redirect_to book_path(@book_new.id), notice: "successfully"
    else
      @user = User.find(current_user.id.to_s)
      @books = Book.all
      # @book = Book.find(id: params[:id])
      # @book.user.name = User.find_(current_user.id.to_s).name
      render :index
    end
  end

  def edit
    @book = Book.find_by(id: params[:id])
  end

  def update
    @book = Book.find_by(id: params[:id])
    if @book.update(book_params)
      redirect_to book_path(id: params[:id]), notice: "successfully"
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
    #params.permit(:title, :body, :id)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @user = User.find(current_user.id.to_s)
    @book = Book.new
    @book.user_id = current_user.id
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @book.user_id = current_user.id
    @books = Book.all
  end

  def edit
    @user = User.find(current_user.id.to_s)
  end

  def update
    @user = User.find(current_user.id.to_s)
    if @user.update(user_params)
      redirect_to user_path(current_user.id.to_s), notice: "successfully"
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(user_path(current_user.id.to_s)) unless @user == current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

        <div id="error_explanation">
          <% if @book.errors.any? %>
            <h3>
              <%= @book.errors.count %> error prohibited this obj from being saved:
            </h3>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title ,class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body ,class: "form-control book_body"%>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book" ,class: "btn btn-success" %>
        </div>
        <% end %>
        <%= link_to "Show",book_path(params[:id]) %>
        |
        <%= link_to "Back",books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <div id="error_explanation">
      <% if @book_new.errors.any? %>
        <h3>
          <%= @book_new.errors.count %> error prohibited this obj from being saved:
        </h3>
        <ul>
          <% @book_new.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>

  <div class="row">
    <div class="col-md-3">
      <!--User infoに関する記載-->
      <%= render 'users/user_info', user: @user %>

      <!--New bookに関する記載-->
      <%= render 'users/new_book', book: @book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        <tbody>
          <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td>
                    <%= book.body %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
  <div id="error_explanation">
    <% if @book_new.errors.any? %>
      <h3>
        <%= @book_new.errors.count %> error prohibited this obj from being saved:
      </h3>
      <ul>
        <% @book_new.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

    <div class="col-md-3">
      <!--User infoに関する記載-->
      <%= render 'users/user_info', user: @user %>

      <!--New bookに関する記載-->
      <%= render 'users/new_book', book: @book_new %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id) do %>
                  <%= image_tag @book.user.get_profile_image(100,100) %>
                  <p><%= @book.user.name %></p>

                <% end %>
              </td>
              <td>
                <%= link_to book_path(@book.id) do %>
                  <%= @book.title %>
                <% end %>
              </td>
              <td>
                  <%= @book.body %>
              </td>

              <% if current_user.id.to_s == @book.user_id.to_s %>
                <td>
                    <%= link_to "Edit", edit_book_path(@book.id) , class: "btn btn-sm btn-success" %>
                </td>
                <td>
                    <%= link_to "Destroy", book_path(@book.id) ,method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
                </td>
              <% end %>

            </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/homes/about.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to
      <i class="fas fa-book"></i>
      <strong>Bookers</strong>
      !
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<!--通知表示のために後で利用-->
<p id="notice"></p>
<div class="container">
    <div class="row">
        <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
            <h1>
                welcome to
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>
                !!
            </h1>
            <p>
                In
                <i class="fas fa-book"></i>
                <strong>Bookers</strong>
                ,
            </p>
            <p>you can share and exchange  your opinions , inpressions , and emotions</p>
            <p>about various books!</p>
            <div class="btn-wrapper col-10 mx-auto">
                <div class="row">
                    <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
                </div>
                <div class="row">
                    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/163b8cc948.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark d-flex">
        <div class="container">

          <%= link_to "Bookers", root_path,class: "navbar-brand" %>

            <!--ハンバーガーメニュー作成-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>


          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <div class= "nav-link text-light">
                    <i class="fas fa-home" aria-hidden="true"></i>
                    <%= link_to "Home", user_path(current_user.id) , class: "text-light" %>
                  </div>
                </li>
                <li class="nav-item active"  aria-hidden="true">
                  <div class= "nav-link text-light">
                    <i class="fas fa-users"></i>
                    <%= link_to "Users", users_path ,class: "text-light"%>
                  </div>
                </li>
                <li class="nav-item active">
                  <div class= "nav-link text-light">
                    <i class="fas fa-book-open"></i>
                    <%= link_to "Books", books_path ,class: "text-light"%>
                  </div>
                </li>
                <li class="nav-item active">
                  <div class= "nav-link text-light">
                    <i class="fas fa-sign-out-alt"></i>
                    <%= link_to " Log out", destroy_user_session_path, method: :delete ,class: "text-light" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item active">
                  <div class= "nav-link text-light">
                    <i class="fas fa-home" aria-hidden="true"></i>
                    <%= link_to "Home", root_path, class: "text-light" %>
                  </div>
                </li>
                <li class="nav-item active"  aria-hidden="true">
                  <div class= "nav-link text-light">
                    <i class="fas fa-link"></i>
                    <%= link_to "About", about_home_path ,class: "text-light"%>
                  </div>
                </li>
                <li class="nav-item active">
                  <div class= "nav-link text-light">
                    <i class="fas fa-user-plus"></i>
                    <%= link_to "Sign up", new_user_registration_path ,class: "text-light"%>
                  </div>
                </li>
                <li class="nav-item active">
                  <div class= "nav-link text-light">
                    <i class="fas fa-sign-in-alt"></i>
                    <%= link_to "Log in", new_user_session_path ,class: "text-light"%>
                  </div>
                </li>
              <% end %>
            </ul>
          </div>

        </div>
    </nav>
  </header>
  <main "mb-auto">
    <p class="notice"><%= notice %><%= alert %></p>

    <%= yield %>
  </main>
  <footer class="footer">
    <div class="container mt-5">
      <div class="row d-flex justify-content-center">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>
  </body>
</html>

app/views/users/_new_book.erb
      <!--New bookに関する記載-->
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title ,class: "form-control book_title" %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Option</label>
          <%= f.text_area :body ,class: "form-control book_body"%>
        </div>

        <div class="form-group">
          <%= f.submit "Create Book" ,class: "btn btn-success" %>
        </div>

      <% end %>

app/views/users/_user_info.erb
      <!--User infoに関する記載-->
      <h2>User info</h2>
      <%= image_tag user.get_profile_image(100,100) %>

      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>

        </tbody>
      </table>
      <div class="row">
        <!--Iconをlink_toを利用して表示させる方法が分からない-->
        <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block",method: :get do%>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <div id="error_explanation">
          <% if @user.errors.any? %>
            <h3>
              <%= @user.errors.count %> error prohibited this obj from being saved:
            </h3>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <%= form_with model: @user do |f| %>
          <div class="form-group">
            <label for="user_name">Name</label>
            <%= f.text_field :name ,class: "form-control book_title" %>
          </div>

          <div class="form-group">
            <label for="user_image">Image</label> </br>
            <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
          </div>

          <div class="form-group">
            <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction ,class: "form-control book_body"%>
          </div>
          <div class="form-group">
            <%= f.submit "Update User" ,class: "btn btn-secondary" %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--User infoに関する記載-->
      <%= render 'user_info', user: @user %>

      <!--New bookに関する記載-->
      <%= render 'new_book', book: @book %>

    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
        <tbody>
          <% @users.each do |user| %>
              <tr>
                <td>
                  <%= image_tag user.get_profile_image(100,100) %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  <%= link_to "Show" ,user_path(user.id) %>
                </td>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <!--User infoに関する記載-->
      <%= render 'user_info', user: @user %>

      <!--New bookに関する記載-->
      <%= render 'new_book', book: @book %>

    </div>

    <div class="col-md-8 offset-md-1">

      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        <tbody>
          <% @books.each do |book| %>

            <% if book.user_id.to_s == params[:id].to_s %>
              <tr>
                <td>
                  <%= link_to user_path(book.user_id) do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td>
                    <%= book.body %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>